# fly.toml app configuration file generated for shuttle-7-26 on 2025-08-02T17:30:28Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'shuttle-7-26'
primary_region = 'ewr'

[build]

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
